version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: 
          name: Build
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test

      - store_test_results:
          path: test/unit/coverage

      - store_artifacts:
          path: test/unit/coverage

      - run:
          command: bash <(curl -s https://codecov.io/bash)